### bank_fe - dev mode
#1. use base image
FROM node:20

#2.set working directory
WORKDIR /app

#3. copy package + install
COPY package*.json ./
RUN npm install

#4. copy app code
COPY . .

#5. start app, bind to 0.0.0.0
CMD ["npx", "vite", "--host", "0.0.0.0"]
